Repository knative-sandbox/eventing-camel, pull requests merged in 2020-11, with the labels that each got.

#26 Set SYSTEM_NAMESPACE to knative-eventing to fix tests
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#25 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#29 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/S

#31 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#32 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#33 Fix a few more occurrences of divisive language
  config/placeholder.go
Labels: approved, cla: yes, lgtm, size/XS
