Repository knative-sandbox/eventing-camel, pull requests merged in 2020-10, with the labels that each got.

#11 Upgrade and fix e2e tests
  .github/workflows/kind-e2e.yaml
  .gitignore
  test/e2e/camel_source_test.go
Labels: approved, cla: yes, lgtm, size/M

#12 Backport fixes to tests in 0.18
  .github/workflows/kind-e2e.yaml
  .gitignore
  test/e2e/camel_source_test.go
Labels: approved, cla: yes, lgtm, size/M

#14 Upgrade to Camel K 1.2.0
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  pkg/reconciler/resources/integration_test.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/build_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/common_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integration_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integration_types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationkit_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/integrationplatform_types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/knative/types.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/knative/types_support.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/register.go
  vendor/github.com/apache/camel-k/pkg/apis/camel/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#15 leverage new test-infra go_update_deps
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#17 Remove deprecated images
  hack/tools.go
  vendor/knative.dev/eventing/test/test_images/filterevents/main.go
  vendor/knative.dev/eventing/test/test_images/filterevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sequencestepper/main.go
  vendor/knative.dev/eventing/test/test_images/sequencestepper/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#21 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL
