Repository knative-sandbox/eventing-camel, pull requests merged in 2021-04, with the labels that each got.

#89 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#91 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/camelsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/camelsource/state.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/test/performance/infra/aggregator/aggregator.go
  vendor/knative.dev/eventing/test/performance/infra/receiver/receiver.go
  vendor/knative.dev/eventing/test/performance/infra/sender/http_load_generator.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/network/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#92 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#93 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#95 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#96 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/camelsource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S

#98 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/camelsource/reconciler.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#99 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/L

#100 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#101 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/fake/fake_apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/fake/fake_containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/fake/fake_sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha2/sources_client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#97 Deprecate the CamelSource controller
  README.md
Labels: approved, cla: yes, lgtm, size/S

#102 [Automated] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/S
