Repository knative-sandbox/eventing-camel, pull requests merged in 2021-01, with the labels that each got.

#35 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#38 Fix ko setup
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#40 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#41 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#42 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/populate_span_transformer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#44 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#45 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/sources/v1alpha1/camelsource/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#47 [] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/camel-k/injection/informers/camel/v1/build/filtered/build.go
  pkg/camel-k/injection/informers/camel/v1/build/filtered/fake/fake.go
  pkg/camel-k/injection/informers/camel/v1/camelcatalog/filtered/camelcatalog.go
  pkg/camel-k/injection/informers/camel/v1/camelcatalog/filtered/fake/fake.go
  pkg/camel-k/injection/informers/camel/v1/integration/filtered/fake/fake.go
  pkg/camel-k/injection/informers/camel/v1/integration/filtered/integration.go
  pkg/camel-k/injection/informers/camel/v1/integrationkit/filtered/fake/fake.go
  pkg/camel-k/injection/informers/camel/v1/integrationkit/filtered/integrationkit.go
  pkg/camel-k/injection/informers/camel/v1/integrationplatform/filtered/fake/fake.go
  pkg/camel-k/injection/informers/camel/v1/integrationplatform/filtered/integrationplatform.go
  pkg/camel-k/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/camel-k/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  pkg/client/injection/informers/sources/v1alpha1/camelsource/filtered/camelsource.go
  pkg/client/injection/informers/sources/v1alpha1/camelsource/filtered/fake/fake.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/duck/channel.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/duck/subscriber.go
  vendor/knative.dev/eventing/test/lib/duck/resource_creators.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
